### ISSUE TITLE
代码的使用

### ISSUE THREAD

**Issue by XanderWangXY** [WenhaoYu1998/LDP#1]
大佬你好！最近看了你们的论文，我十分感兴趣，我看你们的代码是借鉴了[diffusion_policy](https://github.com/real-stanford/diffusion_policy)这个项目吧，你们的代码该如何使用呢，相比于他们做了哪些改动呢。期待得到你们的解答！

**Comment by WenhowYu** [comment]
> 大佬你好！最近看了你们的论文，我十分感兴趣，我看你们的代码是借鉴了[diffusion_policy](https://github.com/real-stanford/diffusion_policy)这个项目吧，你们的代码该如何使用呢，相比于他们做了哪些改动呢。期待得到你们的解答！

您好！非常感谢您的关注！是的，我们是用得diffusion policy的代码。我最近因为一些个人原因耽搁了，后续我会陆续更新仿真器的使用、数据收集与处理、专家策略训练、diffusion policy的训练和推理等代码与教程，预计最晚这个月底会陆续更新完毕。

**Comment by XanderWangXY** [comment]
好的，十分感谢

**Comment by WenhowYu** [comment]
> 好的，十分感谢

您好，相关代码已进行更新，感谢关注！有问题欢迎随时沟通。
