### ISSUE TITLE
Enquire about the type of action sequence in dataset. 

### ISSUE THREAD

**Issue by cutups5** [WenhaoYu1998/LDP#2]
It is position control or velocity control?

Thank you for your concern and sharing.

**Comment by WenhowYu** [comment]
Hello, thank you for your question. 
The action sequence in the dataset is velocity control. The action space dimension is 2, which are the linear velocity and front wheel angle of the Ackerman vehicle.

**Comment by WenhowYu** [comment]
And the value ranges of the two action dimensions are $v \in [-0.6, 0.6]$ and $\theta \in [-0.785, 0.785]$ respectively.

**Comment by cutups5** [comment]
thank you very much. I would like to use your dataset in my new project.
